# Generated by Django 4.0.5 on 2022-06-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCursosyEventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='fecha',
            field=models.DateTimeField(default='21-06-2022'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventos',
            name='fecha',
            field=models.DateTimeField(default='2022-06-21'),
            preserve_default=False,
        ),
    ]
