# Generated by Django 4.0.5 on 2022-06-24 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCursosyEventos', '0002_alumnos_profesores_delete_eventos_cursos_comision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumnos',
            options={'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AlterModelOptions(
            name='cursos',
            options={'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='profesores',
            options={'verbose_name_plural': 'Profesores'},
        ),
    ]
