# Generated by Django 4.0.5 on 2022-07-05 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCursosyEventos', '0003_alter_alumnos_options_alter_cursos_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnos',
            old_name='nacimiento',
            new_name='fecha_nacimiento',
        ),
    ]
