# Generated by Django 4.0.5 on 2022-06-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCursosyEventos', '0003_remove_cursos_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='fecha',
            field=models.DateTimeField(default='2022-06-21'),
            preserve_default=False,
        ),
    ]
